---
# tasks file for newrelic

################# add repo ########################
- name: add newrelic repo
  apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: add newrelic repo centos
  yum: name=https://yum.newrelic.com/pub/newrelic/el5/x86_64/newrelic-repo-5-3.noarch.rpm state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: add apt key
  apt_key: url='https://download.newrelic.com/548C16BF.gpg' state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

############### install ##########################
- name: install newrelic package
  apt: name=newrelic-sysmond state=present update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install newrelic package centos
  yum: name=newrelic-sysmond state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

############## add license #########################
- name: add license key to config
  shell: nrsysmond-config --set license_key="{{ license }}"
  tags:
   - keys
  notify:
     - Restart newrelic
