---
# tasks file for newrelic
- name: add newrelic repo
  apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present

- name: add apt key
  apt_key: url='https://download.newrelic.com/548C16BF.gpg' state=present

- name: install newrelic package
  apt: name=newrelic-sysmond state=present update_cache=yes

- name: add license key to config
  shell: nrsysmond-config --set license_key="{{ license }}"
  tags:
   - keys
  notify:
     - Restart newrelic
